export const GamePhase = {
  SELECT_CATEGORY: "SELECT_CATEGORY",
  WAIT_FOR_COUNTDOWN: "WAIT_FOR_COUNTDOWN",
  ROLL_DICE: "ROLL_DICE",
  SELECT_WORD: "SELECT_WORD",
  SELECT_HIT_OR_MISS: "SELECT_HIT_OR_MISS",
  GAME_OVER: "GAME_OVER"
};
