export const WsMessageTypes = {
  USER_JOINED: "USER_JOINED",
  GAME_START: "GAME_START",
  NEXT_PLAYER: "NEXT_PLAYER",
  CATEGORY_CHOSEN: "CATEGORY_CHOSEN",
  CATEGORY_SELECTED: "CATEGORY_SELECTED",
  HEARTBEAT: "HEARTBEAT",
  ERROR: "ERROR",
};